### PR TITLE
Diana.akhmedova

### PR DESCRIPTION
**Pull request by dakhmedova30**
Populated and worked on DailyView.java

### CODE REVIEW

**Review by KushGandhi3 — CHANGES_REQUESTED** [review]
Please remove HourlyView.java as it has been renamed to DailyView.

**Comment by dakhmedova30** [comment]
Removed HourlyView.

**Review by daniilio — APPROVED** [review]
The view looks good and the file name now uses "daily".

**Review by daniilio — APPROVED** [review]
HourlyView has been renamed to DailyView as needed

**Review by KushGandhi3 — APPROVED** [review]
Looks good. Please start implementing your use case.

**Pull request merged**
