### PR TITLE
Daniil.trukhin

### PR DESCRIPTION
**Pull request by daniilio**
I updated and tested RecentCitiesDAO to make sure it worked as expected. Refactored and modified reading and writing.

### CODE REVIEW

**Review by KushGandhi3 — CHANGES_REQUESTED** [review]
OpenCV is not necessary for our project, please remove it from the Pom.xml.

**Review by KushGandhi3 — CHANGES_REQUESTED** [review]
Avoid wild card imports to ensure consistent styling across all files.

**Comment by daniilio** [comment]
Finished and tested InMemoryWeatherDAO

**Comment by daniilio** [comment]
implemented your requests

**Review by Kurochiisu — APPROVED** [review]
Looks good to me! The changes that were requested previously have been implemented.

**Review by KushGandhi3 — APPROVED** [review]

**Pull request merged**
